var first_name="Ranbir ";
var last_name="Kapoor";
var full_name=first_name.concat(last_name);
console.log(full_name);
var a=10;
var b=5;
var add=a+b;
var sub=a-b;
var into=a*b;
var div=a/b;
console.log(add);
console.log(sub);
console.log(into);
console.log(div);